export const ACTIVITIES = [
  { code: '111000', name: 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas' },
  { code: '151000', name: 'Elaboración y conservación de carne y productos cárnicos' },
  { code: '181000', name: 'Fabricación de prendas de vestir' },
  { code: '281000', name: 'Fabricación de productos metálicos para uso estructural' },
  { code: '451000', name: 'Construcción de edificios' },
  { code: '471100', name: 'Venta al por menor en comercios no especializados, con predominio de prod. alimenticios' },
  { code: '471900', name: 'Venta al por menor en comercios no especializados, sin predominio de prod. alimenticios' },
  { code: '478100', name: 'Venta al por menor en puestos de venta y mercados' },
  { code: '491000', name: 'Transporte ferroviario' },
  { code: '492000', name: 'Transporte automotor de cargas' },
  { code: '493000', name: 'Transporte automotor de pasajeros' },
  { code: '561000', name: 'Restaurantes y actividades de servicio de comidas' },
  { code: '562000', name: 'Suministro de comidas por encargo' },
  { code: '563000', name: 'Servicio de bebidas' },
  { code: '620100', name: 'Actividades de programación informática' },
  { code: '620200', name: 'Actividades de consultoría informática' },
  { code: '620900', name: 'Otras actividades de tecnología de la información y de informática' },
  { code: '630000', name: 'Actividades de servicios de información' },
  { code: '641000', name: 'Banca central' },
  { code: '649000', name: 'Actividades de financiamiento' },
  { code: '680000', name: 'Actividades inmobiliarias' },
  { code: '691000', name: 'Actividades jurídicas' },
  { code: '692000', name: 'Actividades de contabilidad, teneduría de libros y auditoría' },
  { code: '693000', name: 'Actividades de arquitectura e ingeniería' },
  { code: '701000', name: 'Actividades de oficinas centrales' },
  { code: '702000', name: 'Actividades de consultoría de gestión' },
  { code: '711000', name: 'Actividades de arquitectura e ingeniería' },
  { code: '731000', name: 'Publicidad' },
  { code: '741000', name: 'Actividades especializadas de diseño' },
  { code: '742000', name: 'Actividades de fotografía' },
  { code: '749000', name: 'Otras actividades profesionales, científicas y técnicas n.c.p.' },
  { code: '751000', name: 'Actividades veterinarias' },
  { code: '810000', name: 'Actividades de servicios a edificios y paisajismo' },
  { code: '821000', name: 'Actividades administrativas y de apoyo de oficina' },
  { code: '841100', name: 'Actividades de la administración pública en general' },
  { code: '850000', name: 'Enseñanza' },
  { code: '851000', name: 'Enseñanza preprimaria' },
  { code: '852000', name: 'Enseñanza primaria' },
  { code: '853000', name: 'Enseñanza secundaria' },
  { code: '854000', name: 'Enseñanza superior' },
  { code: '855000', name: 'Otras actividades de enseñanza' },
  { code: '860000', name: 'Actividades de atención de la salud humana' },
  { code: '861000', name: 'Actividades de hospitales' },
  { code: '862000', name: 'Actividades de médicos y odontólogos' },
  { code: '869000', name: 'Otras actividades de atención de la salud humana' },
  { code: '900000', name: 'Actividades creativas, artísticas y de entretenimiento' },
  { code: '960000', name: 'Otras actividades de servicios personales' },
  { code: '961000', name: 'Actividades de peluquería y otros tratamientos de belleza' },
  { code: '969000', name: 'Otras actividades de servicios personales n.c.p.' },
]
